name: pip_clients_email
version: 1.0.0
author: Sergey Seroukhov
description: Email Microservice
homepage: https://github.com/

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  pip_services3_commons: ">=1.0.7 <2.0.0"
  pip_services3_components: ">=1.0.2 <2.0.0"
  pip_services3_data: ">=1.0.0 <2.0.0"
  pip_services3_rpc: ">=1.0.2 <2.0.0"
  pip_services_email: ">=1.0.0 <2.0.0" 
  http: "^0.12.0"
  angel_framework: ^2.1.1

dev_dependencies:
  test: '>=1.14.2 <2.0.0'
